### ISSUE TITLE
More descriptive errors like a compiler

### ISSUE THREAD

**Issue by gaigepr** [kubernetes-sigs/kustomize#124]
It would be nice if kustomize could print more context when it occurs an error. Errors like the one below are not helpful.

```
$ kustomize build overlays/docker-for-desktop/
Error: <nil> is not expected to be a primitive type
```

**Comment by Liujingfang1** [comment]
@gaigepr Can you also paste your YAML files?

**Comment by gaigepr** [comment]
I do not have the files that presented this error but I can tell you that it was caused by bad indentation such that the `containers` object was misaligned inside a `deployment.spec`.

More generally, I think it would be nice if anytime kustomize encountered an error, it could print some sort of stack trace or more descriptive error to help the developer know where the issue is.

**Comment by Liujingfang1** [comment]
should have been fixed by #117

**Comment by laverya** [comment]
Are there any plans to address this? Issue #117 says that it's a duplicate of this issue and will be addressed here, (https://github.com/kubernetes-sigs/kustomize/issues/117#issuecomment-398568924) but this issue was closed in favor of #117...
It feels like one of the two should have remained open.

In any case, I still see this in [v1.0.8](https://github.com/kubernetes-sigs/kustomize/releases/tag/v1.0.8) running on macOS 10.14, so I do not believe it has been fixed.

**Comment by Liujingfang1** [comment]
@laverya Sorry for this confusion. We will address this issue. Can you provide an example? Is the failure only on macOS?

**Comment by laverya** [comment]
I don't believe this is a mac-specific bug issue - more one with how errors are generated on all platforms. 

An example:

base/kustomization.yaml:
```
kind: ""
apiversion: ""
resources:
- deployment.yaml
```

base/deployment.yaml:
```
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
        release: "test"
    spec:
      containers:
      - name: test
        image: "atest/image"
        imagePullPolicy: IfNotPresent
        env:
```

Running `kustomize build base/` from the parent directory yields `Error: <nil> is not expected to be a primitive type`.

Yes, the yaml for the deployment is invalid - but it would be nice to know what file was invalid, if not the specific key. (if `env:` is changed to `env: {}`  things will work)
