### ISSUE TITLE
[kustomize 2.1.0] cannot read data from configMap 

### ISSUE THREAD

**Issue by jinchihe** [kubernetes-sigs/kustomize#1295]
I hit the problem with kustomize 2.1.0, but that works fine with kustomize 2.0.3, I'm not sure is that broken by kustomize 2.1.0 or design behavior changed?

Base kustomization.yaml
```
[root@jinchi1 local]# cat ../base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
vars:
...
- fieldref:
    fieldPath: data.batchSize
  name: batchSize
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
...
```
Local kustomization.yaml
```
[root@jinchi1 local]# cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base
.....
configMapGenerator:
- literals:
  - name=mnist-train-local
  - batchSize=100
 ....
  name: mnist-map-training
```
[root@jinchi1 local]# kustomize build .
Error: var '{batchSize ~G_~V_ConfigMap {data.batchSize}}' cannot be mapped to a field in the set of known resources
[root@jinchi1 local]# kustomize version
Version: {KustomizeVersion:2.1.0 GitCommit:af67c893d87c5fb8200f8a3edac7fdafd61ec0bd BuildDate:2019-06-18T22:01:59Z GoOs:linux GoArch:amd64}

But **that works fine with kustomize v0.2.3**. Could someone to take a look? thanks a lot!

**Comment by jinchihe** [comment]
/cc @monopole @Liujingfang1 
Any suggestion for this? Or recommend someone to take a look? Great thanks!

**Comment by jinchihe** [comment]
Did more deep tests, if both of `vars` and `configMapGenerator` are in same kustomization.yaml, that's OK. In other words, both the `vars` and `configMapGenerator` need to in `base/kustomization.yaml` or both in `local/kustomization.yaml`. But failed if `var` defined in `base`, and `configMapGenerator` defined in `local/kustomization.yaml`.

Personally we should fix that, for reasons:
1. For most the cases, The `var` path will be same, user would like to set in the base, but the value is not same, user would like to set in local.
2. kustomize v2.0.3 supports that, we should have basic compatibility.

**Comment by monopole** [comment]
nice report thanks.

any chance you could help us by writing a test demonstrating this that we can keep for regression coverage?

like [this](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/target/variableref_test.go#L380) but focussed on your particular case?

we're a little shorthanded here. :)

**Comment by jinchihe** [comment]
Not sure I have chance for this, since many workloads accumulation :-( apologize... but will do that if get chance. I think we can fix that and then writing a test demonstrating.

**Comment by jbrette** [comment]
@jinchihe This is fixed by [PR](https://github.com/kubernetes-sigs/kustomize/pull/1316).

Did reproduce your issue [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1295) using some of them minst CRDs.

@monopole The corresponding go regression test is [here](https://github.com/kubernetes-sigs/kustomize/pull/1316/files#diff-370b113fc81c0dcde25bec5c099d0573R298)

**Comment by ryandawsonuk** [comment]
I see https://github.com/kubernetes-sigs/kustomize/pull/1316 was closed without merging and the problem that led to this [still affects](https://github.com/kubeflow/examples/issues/681#issue-526630577) the most recent versions of kustomize v2 and v3. Are we any closer to deciding whether this is to be considered a bug that should be fixed or if it's to be thought of as by design?

**Comment by jinchihe** [comment]
The problem still exists in kustomize v3.4.0.

```
# /test123/kustomize version
{Version:kustomize/v3.4.0 GitCommit:2c9635967a2b1469d605a91a1d040bd27c73ca7d BuildDate:2019-11-12T05:00:57Z GoOs:linux GoArch:amd64}
# /test123/kustomize build .
Error: var '{batchSize ~G_v1_ConfigMap {data.batchSize}}' cannot be mapped to a field in the set of known resources
```
/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by jinchihe** [comment]
@jbrette @monopole Could you please help to double confirm and fix this? thanks a lot!
/P1

**Comment by igorcalabria** [comment]
This issue still persists in kustomize v4.2.0. If the generator and vars are defined in the same file it works, but if the var is on one file(say base, for example) and the generator is on another file(production) it won't work.

**Comment by a-nych** [comment]
/reopen
/remove-lifecycle rotten

Reopening as this still persists in v4.5.2

**Comment by a-nych** [comment]
@monopole Could you please reopen this issue?

**Comment by Kristin0** [comment]
@monopole Could you please reopen this issue?

**Comment by tingsl409** [comment]
An old issue, might not be relavent anymore but I found that changing the overlays generator behavior to merge could solve the issue:

base/kustomization.yml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deployment.yml

configMapGenerator:
- name: gg

vars:
- name: TEST
  objref:
    kind: ConfigMap
    name: gg
    apiVersion: v1
  fieldref:
    fieldpath: data.wut
```
overlays/local/kustomization.yml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
- name: gg
  behavior: merge
  literals:
  - wut=helloWorld
```
At least it works in my environment .
