### ISSUE TITLE
multi-protocol in single port is not supported

### ISSUE THREAD

**Issue by KimMJ** [kubernetes-sigs/kustomize#2934]
It seems `kustomize` does not support "same port, different protocol" service.
Here is my test:

### Files

```bash
kustomize
├── kustomization.yaml
├── service-patch.yaml
└── service.yaml
```

#### service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 1234
    name: test-tcp
    protocol: TCP
  - port: 1234
    name: test-udp
    protocol: UDP
```

#### service-patch.yaml
```yaml
kind: Service
metadata:
  name: myapp
  labels:
    test: label
```

#### kustomization.yaml
```yaml
resources:
  - service.yaml
patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: myapp
```

### Command

```bash
$ kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T17:44:01Z GoOs:linux GoArch:amd64}

$ kustomize build .
apiVersion: v1
kind: Service
metadata:
  labels:
    test: label
  name: myapp
spec:
  ports:
  - name: test-tcp
    port: 1234
    protocol: TCP
  - name: test-tcp
    port: 1234
    protocol: TCP
  selector:
    app: myapp
```
---

As you can see, after kustomize build to add `test=label` label in Service type,
`test-udp` port is changed to TCP protocol and its name so that `Kubernetes` throw an duplicated port name error. 

`Kubernetes` could use multiple protocol with same port like this:

```bash
$ kubectl get svc myapp 
NAME    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
myapp   ClusterIP   10.96.223.96   <none>        1234/TCP,1234/UDP   12m
```

but `kustomize` couldn't make it.

**Comment by Shell32-Natsu** [comment]
dup with #2767. We are working on it but it's not a simple fix.

**Comment by KimMJ** [comment]
thanks @Shell32-Natsu . then I close this

**Comment by lackhoa** [comment]
This issue was closed, but has the issue been fixed?

**Comment by natasha41575** [comment]
@lackhoa Yes, the issue has been fixed with the introduction of https://github.com/kubernetes-sigs/kustomize/pull/3159

The merge key for service ports has been changed from [port] to [port, protocol].

**Comment by lackhoa** [comment]
@natasha41575 I tested this on `3.9.2` and it's not working (but the OP's case worked):

# kustomization.yaml

```
resources:
  - resource.yaml
patches:
  - path: patch.yaml
    target:
      kind: StatefulSet
      name: myapp
```

# resource.yaml

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: consul
          image: "hashicorp/consul:1.9.1"
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8501
              name: https
            - containerPort: 8301
              protocol: "TCP"
              name: serflan-tcp
            - containerPort: 8301
              protocol: "UDP"
              name: serflan-udp
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server
            - containerPort: 8600
              name: dns-tcp
              protocol: "TCP"
            - containerPort: 8600
              name: dns-udp
              protocol: "UDP"
```

# patch.yalm

```
kind: StatefulSet
metadata:
  name: myapp
  labels:
    test: label
```

# Result:

```
kustomize build .
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    test: label
  name: myapp
spec:
  template:
    spec:
      containers:
      - image: hashicorp/consul:1.9.1
        name: consul
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8501
          name: https
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8302
          name: serfwan
        - containerPort: 8300
          name: server
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
```

**Comment by natasha41575** [comment]
@lackhoa would you mind filing a new issue for your use case and tagging me? I will start investigating this today and Monday

**Comment by yydzhou** [comment]
@natasha41575 Here is the new issue. I have updated my binary to newest version and the problem still exists. I am assuming it's a simple fix, since it already supported in statefulset test case.
https://github.com/kubernetes-sigs/kustomize/issues/4752
