### ISSUE TITLE
`helmCharts` repo field doesn't work with OCI registry

### ISSUE THREAD

**Issue by QuinnBast** [kubernetes-sigs/kustomize#4381]
**Describe the bug**

Kustomize fails to pull charts through `helmCharts` yaml that are hosted within an OCI registry.

** Example **

Create a `kustomize.yaml` file:

```
helmCharts:
  - name: someName
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: myRelease
    version: 0.0.26
    repo: oci://myRegistry
```

Run the command `kustomize build --enable-helm --helm-command $helmCommand ./folder`

Kustomize will fail to pull the helm chart and produce the following error:

```
Error: Error: looks like "oci://myRegistry" is not a valid chart repository or cannot be reached: object required
: unable to run: '/usr/sbin/helm pull --untar --untardir <someDir> --repo oci://myRegistry myRelease --version 0.0.26' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-991395685/helm HELM_CACHE_HOME=/tmp/kustomize-helm-991395685/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-991395685/helm/.data] (is '/usr/sbin/helm' installed?)
```

Running a regular `helm pull` works fine on the registry, but pulling with `--repo` causes issues:
```
# Working
$ helm pull oci://myRegistry/myRelease --version 0.0.26
Pulled: myRegistry/myRelease:0.0.26
Digest: sha256:14e1bc1ec1d0147eb8b41f081faae2ecea63e862ad4259d3a9cd1c7d1584be63

# Not working with `--repo`
$ helm pull myRelease --version 0.0.26 --repo myRegistry
Error: could not find protocol handler for: 

$ helm pull myRelease --version 0.0.26 --repo oci://myRegistry
Error: looks like "oci://myRegistry" is not a valid chart repository or cannot be reached: object required
```

I also cannot work around this by just adding it as a repo:
```
$ helm repo add reg myRegistry
Error: could not find protocol handler for: 

$ helm repo add reg oci://myRegistry
Error: looks like "oci://myRegistry" is not a valid chart repository or cannot be reached: object required
```

**Expected output**

Expected Kustomize to be able to pull the chart and apply the `values.yaml` to the chart. The solution would be for `oci://` urls, to not use the `--repo` flag when performing a helm pull.

**Kustomize version**

$ kustomize version
{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:24:28Z GoOs:linux GoArch:amd64}

$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

**Platform**

Ubuntu

**Comment by KlavsKlavsen** [comment]
Kostumize 3.8.0 was just released with the new OCI support moved to 'production' status - this implements the changes that was done in 3.7.1 as stable (no longer experiemental env needed to use it in Helm) :)

**Comment by QuinnBast** [comment]
I upgraded to helm 3.8.0 and am getting the same error. The use of `--repo` is problematic for oci registries.

```
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

```
$ kustomize build --enable-helm ./test
Error: Error: looks like "oci://myRegistry" is not a valid chart repository or cannot be reached: object required
: unable to run: 'helm pull --untar --untardir <someDir> --repo oci://myRegistry myRelease --version 0.0.26' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-991395685/helm HELM_CACHE_HOME=/tmp/kustomize-helm-991395685/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-991395685/helm/.data] (is 'helm' installed?)
```

Can pull without specifying `--repo`:
```
$ helm pull oci://myRegistry --version 0.0.26
Pulled: myRegistry/myRelease:0.0.26
Digest: sha256:14e1bc1ec1d0147eb8b41f081faae2ecea63e862ad4259d3a9cd1c7d1584be63
```

Cannot pull with `--repo`
```
$ helm pull myRelease --version 0.0.26 --repo myRegistry
Error: could not find protocol handler for: 

$ helm pull myRelease --version 0.0.26 --repo oci://myRegistry
Error: looks like "oci://myRegistry" is not a valid chart repository or cannot be reached: object required
```


[This seems to be the issue](https://github.com/kubernetes-sigs/kustomize/blob/d9435bd1b13a6764b9d271001e61837199494d1c/api/builtins/HelmChartInflationGenerator.go#L294). Maybe if the repo is `oci://` you can make this not use the `--repo` flag?

**Comment by tis-rpage** [comment]
If anyone takes the above patch, I think they should note the trailing comma needs fixing:
```diff
- 		"--untardir", p.absChartHome(),
+ 		"--untardir", p.absChartHome()
```

> I am unable to make a MR because I can't sign the CLA but can someone make this MR for me?
> 
> [This line should be](https://github.com/kubernetes-sigs/kustomize/blob/d9435bd1b13a6764b9d271001e61837199494d1c/api/builtins/HelmChartInflationGenerator.go#L294):
> 
> ```diff
> func (p *HelmChartInflationGeneratorPlugin) pullCommand() []string {
> 	args := []string{
> 		"pull",
> 		"--untar",
> 		"--untardir", p.absChartHome(),
> -               "--repo", p.Repo
> -		p.Name}
> +             }
> 	if p.Version != "" {
> 		args = append(args, "--version", p.Version)
> 	}
> +	if strings.HasPrefix(p.Repo, "oci://") {
> +	        args = append(args, p.Repo)
> +	} else {
> +              args = append(args, "--repo", p.Repo)
> +              args = append(args, p.Name)
> +       }
> 	return args
> }
> ```
> 
> This is untested, but `--repo` should not be in the pull command if `oci://` is specified. If `oci://` is specified, just do a straight helm pull

**Comment by minnie-jeong-otsk** [comment]
It'd be greatly appreciated if this fix is deployed soon!

**Comment by natasha41575** [comment]
The Helm plugin builtin into kustomize is being migrated to a [third party KRM extension](https://github.com/kubernetes-sigs/kustomize/issues/4401), in which we will support OCI [[issue]](https://github.com/kubernetes-sigs/krm-functions-registry/issues/11). I will try to prioritize the migration and OCI support in Q2 given that there are a large number of requests for this.

/triage accepted

**Comment by QuinnBast** [comment]
Based off of [this comment](https://github.com/kubernetes-sigs/kustomize/issues/4401#issuecomment-1213360696), it appears that the helm chart inflation tool is supporting bug fixes and adding fields that are normally supported through `helm template`. That would make this issue and #4335 valid and would not be waiting for the new KRM functionality. Is there any priority on these two issues which [already have a fix](https://github.com/QuinnBast/kustomize/commit/64436abd5ca7a81a9f8ea176bbcd136387c592f0)?

**Comment by elamcheliyana** [comment]
I have tried the issue is still present. Does any one when they would consider to fix this problem or it going to be never?

**Comment by igstbagusdharmaputra** [comment]
will this problem be solved soon?

**Comment by LelvProgrammer** [comment]
Bump

**Comment by sthomson-wyn** [comment]
There are PRs to fix this problem in kustomize. KRM is touted as the eventual solution, but has not had a commit in over 9 months...

**Comment by antonydevanchi** [comment]
@mikebz i dare you free blowjob if you close this shit, dude >_<

**Comment by kosta** [comment]
While it is stated under [Long term support ](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support) that

> We will not add support for:
> * OCI registries

I would kindly ask you to reconsider this opinion, given that the fix actually is just +7-2 LOC and the krm function does not support this yet, either.

**Comment by antonydevanchi** [comment]
@kosta nevertheless it uses widely by Yandex.Cloud: [site:cloud.yandex.ru "oci:"](https://www.google.com/search?q=site%3Acloud.yandex.ru+"oci%3A") for example.

**Comment by mikebz** [comment]
I think there is a concern about backwards compatibility here, but the backwards compatibility issue was a side effect of the previous implementation and not an advertised feature.  My vote is to move forward with the proposed PR.

**Comment by andrzejgorski** [comment]
As another ugly workaround, I found the solution:
Running kustomize with `--helm-command ~/tmp/sanitized_helm.sh` 

where `~/tmp/sanitized_helm.sh` is:
```bash
#!/bin/bash
if [[ $@ = pull* ]]; then
    # If the command is `helm pull (..)` skips --repo flag and chartName
    # from command line args to make helm pull run

    # See for explanation why:
    # https://github.com/kubernetes-sigs/kustomize/issues/4381
    arr=(${@//--repo/});  # Skipping --repo
    args="${arr[@]:0:5} ${arr[@]:6}";  # Skipping chartName
else
    args="$@"
fi
cmd="/usr/bin/helm --registry-config ~/.config/helm/registry/config.json $args"
echo "Running '$cmd' " >> /tmp/helm-debug
eval $cmd
```

**Comment by SachithKasthuriarachchi** [comment]
any update on this issue? this will be a great feature for kustomize and it will expand kustomize's adaptations

**Comment by diegoluisi** [comment]
Up!

**Comment by QuinnBast** [comment]
No, it's not in yet.

[This MR](https://github.com/annaliseai/kustomize/pull/1) is not against the actual `kustomize` repository; it will only get in after #5167 is approved by @natasha41575 and a release is created that contains the MR

**Comment by annasong20** [comment]
@natasha41575 I'd like to check my understanding of this issue.

Initially, we planned to support this patch in the KRM Helm function, which would've had increased feature-freedom because of its independence from Kustomize. When progress on KRM functions slowed, we [limited `HelmChartInflationGenerator` changes](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support) to lower maintenance costs.

Just to confirm, we are now open to this patch on `HelmChartInflationGenerator` due to its popularity?

**Comment by annasong20** [comment]
@natasha41575 @QuinnBast or anyone else on this thread: Stemming from my lack of understanding of Helm, is Helm's inability to pull charts with the `--repo` flag a bug on their end? By adding the changes in #5167, 
* are we patching a Helm bug or 
* is the `--repo` behavior intentional and the #5167 changes help Kustomize `HelmChartInflationGenerator` reflect new Helm behavior in relation to OCI

@natasha41575 If this is a Helm bug, I assume we're patching it in Kustomize instead of Helm as a short-term workaround for users?

**Comment by natasha41575** [comment]
@annasong20 discussed offline - we will add support in kustomize for oci registries by having the different commands running that helm provides for oci-based charts.

**Comment by pratik705** [comment]
is this fixed? I still cant use OCI registry with kustomize

**Comment by mrclrchtr** [comment]
Yes it is working. I use it like this::
```
helmCharts:
  - name: spegel
    repo: oci://ghcr.io/spegel-org/helm-charts
    releaseName: spegel
    namespace: spegel
    version: v0.0.23
    valuesFile: values.yaml
```

A few days ago I thought it wasn't working either, until I found out that I had entered the wrong repo URL 🤦 When you do that, you get an auth error that sends you on the wrong track.

**Comment by aabouzaid** [comment]
It's weird that it works with `helmCharts` but not `HelmChartInflationGenerator` :thinking:

**Comment by bshah0408** [comment]
@mrclrchtr 

It is still not working for me  ! 
I tried many ways following this  https://github.com/argoproj/argo-cd/issues/16623#issuecomment-1942885993 
for authentication some-how I am still geting 
`Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c "kustomize build . --enable-helm"` failed exit status 1: Error: Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://olacrdev.azurecr.io/oauth2/token?scope=repository%!A(MISSING)helm%!F(MISSING)quarkus-app%!A(MISSING)pull&service=olacrdevops.azurecr.io: 401 Unauthorized : unable to run: 'helm pull --untar --untardir /tmp/_cmp_server/5624b0b4-1c8e-4175-a558-5658f7c76c7c/appsets/aztest1/auth-service/charts oci://olacrdev.azurecr.io/helm/quarkus-app --version 1.1.0' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-2411246150/helm HELM_CACHE_HOME=/tmp/kustomize-helm-2411246150/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-2411246150/helm/.data] (is 'helm' installed?): exit status 1`

Can I get some help or what worked for authentication to azure oci !
another thing from cluster we have access access to acr which can pull the image without secter but for only kustomize it is not supporting which is really annoying.

**Comment by QuinnBast** [comment]
My understanding is that OCI now works, but you cannot authenticate to private registries still...

https://github.com/kubernetes-sigs/kustomize/issues/4335
