### ISSUE TITLE
Components are not "evaluated after the resources of the parent"

### ISSUE THREAD

**Issue by Miles-Garnsey** [kubernetes-sigs/kustomize#5172]
### What happened?

As outlined in [this](https://github.com/kubernetes-sigs/kustomize/issues/4099#issuecomment-1470934286) comment, the intention of components was to enable modular transformations which run after all overlays have run. Again per that comment, the API design for components states:

```
A kustomization that is marked as a Component has basically the same capabilities as a normal kustomization. The main distinction is that they are evaluated after the resources of the parent kustomization (overlay or component) have been accumulated, and on top of them.
```

When using replacements in an overlay, the replacements are not run after the parent overlay's transformations. 

For example, if I define a kustomization which calls another kustomization as a remote resource, and that remote resource has components which ensure that namespaces within it remain properly aligned/propagated (to `ValidatingWebhookConfiguration ` annotations and `Certificate` `dnsNames` in our case) then those components will not run after a namespace transformer in the parent.

```
kustomization.yaml
overlay/
├─ kustomization.yaml
base/
├─ kustomization.yaml
├─ service.yaml/
├─ certificate.yaml/
component/
├─ kustomization.yaml
```

In the above structure, if the namespace transformer is in the `overlay` directory everything works fine. But if it is in the parent directory it fails to propagate the namespace to `replacements`.

### What did you expect to happen?

We expected that the replacements we defined in a component would pick up namespace values after their parent overlays had run. Instead, the replacements in our components appear to run prior to the namespace transformation in our overlays.

Why do replacements break the design for components, and how do we adopt replacements given that we can no longer run them after our overlays have completed their namespace transformations?

We have been trying to migrate to replacements for 18 months, and my team is becoming concerned that when the v1 API is deprecated kustomize will no longer be a viable solution for us (since we deploy several related operators into different namespaces on a regular basis).

### How can we reproduce it (as minimally and precisely as possible)?

I'm supplying a gist as there are quite a few files here: https://gist.github.com/Miles-Garnsey/23a909cb6f6acb30268c0a1d62fe11eb

There's also a public repo which may be easier to work with [here](https://github.com/Miles-Garnsey/kustomize-problem).

### Expected output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cass-operator-webhook-service
  namespace: new-namespace
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cass-operator-serving-cert
  namespace: new-namespace
spec:
  dnsNames:
  - new-namespace
```

### Actual output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cass-operator-webhook-service
  namespace: new-namespace
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cass-operator-serving-cert
  namespace: new-namespace
spec:
  dnsNames:
  - cass-operator
```

### Kustomize version

5.0.1

### Operating system

MacOS

**Comment by Miles-Garnsey** [comment]
Hi @koba1t, I've just built your branch and tested against my example above. It looks like it is still applying the components before the transformers are fully applied, since the dnsNames in the Certificate.spec are still `cass-operator` and not `new-namespace` as we'd like.

**Comment by Miles-Garnsey** [comment]
Apologies for the slow reply @koba1t, I'm trying to figure out why your branch isn't working for me. It has been deleted now, so I'll work off the branch `master` in the origin.

It looks like maybe your branch has fixed a problem where the namespace transform is in an overlay which is a sibling of a component, but it doesn't appear to work when the namespace transform is in a namespace transform in the parent.

I've pushed a change to my[ example repo](https://github.com/Miles-Garnsey/kustomize-problem) to make the issue clearer. 

I think I'm finding this tricky as there might have been a few different bugs I was experiencing when trying to put the example together, I hope it is clearer now.

**Comment by koba1t** [comment]
Hi @Miles-Garnsey 
I'm so sorry for the delayed response.

Looks like your manifests are working as expected.

We merged the PR that [components are applied after generators, before transformers](https://github.com/kubernetes-sigs/kustomize/pull/5170).

That changes the order of evaluation in `kustomization.yaml` file.
Now,  the order of evaluation in this `kustomization.yaml` is 
```
resources -> components -> namespace Transformer
```
https://gist.github.com/Mlundm/527d196d0fa090defb3597a6525fd3a9#file-overlay_kustomization-yaml

I think if you need to evaluate `namespace Transformer` before `components`, I think you need to put `namespace` in the `base` dir.
If you think I misunderstood this problem, Please tell me!

**Comment by ecoupal-believe** [comment]
I almost have the same problem. From my component, I want to add a metadata.label containing the metadata.name added by the namePrefix of an overlay. The replacement is working but it takes the name from the base instead of the one of the overlay. The only workaround I found is using vars and it's being deprecated. Anything else can work ?

**Comment by Mlundm** [comment]
@ecoupal-believe 

See my previous comment. You create another component to apply namePrefix before your component.

And you only need to apply it once before your component(and likely not after it in your case)

**Comment by ecoupal-believe** [comment]
@Mlundm 

Thank you for your answer,  it's actually working but my problem is still the same. I would need to add a component with the namePrefix for each of my overlays. 

Here is some context: https://gist.github.com/ecoupal-believe/1c143045499afbd196505b5911343254

**Comment by Mlundm** [comment]
@ecoupal-believe 

Its intended so. I don't know if they would be willing to/should/can do a special solution to the problem.
